services:
  db:
    image: postgres:18 # Specifies the PostgreSQL 18 image
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend
    ports:
      - '5432:5432'
  redis:
    image: redis:8.4-alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning --requirepass example
    volumes:
      - cache:/data
    ports:
      - '6379:6379'
volumes:
  cache:
    driver: local